[general]
import = [
    "~/.cache/wal/colors-alacritty.toml",
]

[window]
opacity = 0.8
padding = { x = 12, y = 12 }
dynamic_padding = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "<string>" }
italic = { family = "MesloLGS NF", style = "<string>" }
bold_italic = { family = "MesloLGS NF", style = "<string>" }
size = 9

# [colors.primary]
# background = '#1E1E2E'
# foreground = '#D6D6D6'
#
# [colors.cursor]
# text = '#1E1E2E'
# cursor = '#D9D9D9'
#
# [colors.normal]
# black = '#181A1F'
# red = '#E86671'
# green = '#98C379'
# yellow = '#E5C07B'
# blue = '#61AFEF'
# magenta = '#C678DD'
# cyan = '#54AFBC'
# white = '#ABB2BF'
#
# [colors.bright]
# black = '#5C6370'
# red = '#E86671'
# green = '#98C379'
# yellow = '#E5C07B'
# blue = '#61AFEF'
# magenta = '#C678DD'
# cyan = '#54AFBC'
# white = '#F7F7F7'
#
# [colors.dim]
# black = '#5C6370'
# red = '#74423F'
# green = '#98C379'
# yellow = '#E5C07B'
# blue = '#61AFEF'
# magenta = '#6E4962'
# cyan = '#5C8482'
# white = '#828282'

[colors]
transparent_background_colors = true
